mytest:
	g++ -o ../mytest -O0 tidy.cpp tree.cpp -L/usr/local/lib -ltidy -lboost_filesystem -lboost_system -I/usr/local/include -g
python: 
	g++ -o ../pytest -O0 python_score.cpp tree.cpp -L/usr/local/lib -ltidy -lboost_filesystem -lboost_system -I/usr/local/include -g